# This is a basic workflow to help you get started with Actions
name: Connect to an AWS role from a GitHub repository

# Controls when the action will run. Invokes the workflow on push events but only for the main branch
on:
  workflow_run:
    workflows: [Django CI]
    types:
      - completed

env:
  AWS_REGION: us-west-2 # Change to reflect your Region

# Permissions can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::851725592427:role/initRole #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      # ECR Logins
      - name: Log in to ECR
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 851725592427.dkr.ecr.us-west-2.amazonaws.com
      # Docker Build and Push
      - name: Build Docker
        run: docker build -t 851725592427.dkr.ecr.us-west-2.amazonaws.com/gymcms:gymproject .
      - name: Push Docker
        run: docker push 851725592427.dkr.ecr.us-west-2.amazonaws.com/gymcms:gymproject
